name: build

on:
  push:
    tags: [ v\d+.\d+.\d+ ]
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.16
    strategy:
      matrix:
        go-version: [ 1.16.x ]
    services:
      mqtt:
        image: emqx/emqx:latest
        ports:
          - 1883:1883
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test
        run: make test
        env:
          BROKER_ADDRESS: 'mqtt:1883'
